name: "CI"
on: 
- pull_request
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v14
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build
      run: nix-build
    - name: Linkcheck
      run: nix-shell --run "make linkcheck"
